- src/app/components/App.tsx
Persist mode toggle is working correctly do to previous swapped functionality
> Updated for persist mode

- package.json
- package/README.md
- package/package.json
Updated NPM package to reflect correct version numbers and authors
> NPM package update

- README.md
- package.json
- package/package.json
- [ x] Non-breaking change (fix or feature that would causes existing functionality to work as expected)
Updated project README to include optimization for Recoil 0.1.2 and to include Team Tungsten as contributers
> Updated Project README

- README_KO.md
- package.json
- package/package.json
- src/extension/build/devtools.js
- src/extension/build/manifest.json
lack of names in contributors in KO README.md
added names of recent two groups of contributors
> Jaime[update readme ko ver]added contributors

- package.json
- package/formatFiberNodes.js
- package/index.js
- src/app/components/ComponentGraph/AtomComponentVisual.tsx
- src/extension/build/manifest.json
Flame graph and Ranked graph showed different component rendering times.
Synced duration times with Flame and Ranked Graphs.
> Flame and Ranked Graphs duration times fix

- package/formatFiberNodes.js
- src/app/components/AtomNetwork/AtomNetwork.tsx
- src/extension/build/manifest.json
- src/extension/build/stylesheet.css
prevent the network graph from overlapping and made the legend clickable and show dropdown for the atoms/selector
added css for search bar, legend and dropdown
added some state for dropdowns for atoms and selectors
added a function to render conditionally
> [atomNetwork]improve graphics of atom network

- src/extension/build/stylesheet.css
clean up css for readability
made a default setting for all buttons and input boxes in the components
> cleaned up css to make default setting for buttons and input boxes

- src/app/components/ComponentGraph/AtomComponentVisual.tsx
- src/extension/build/stylesheet.css
add new feature for component graph and refactor css code to render correctly
added some hooks regarding dropdown for the corresponding legends and add !important in css to ignore parent css setting
> [component graph & css]

- src/app/components/ComponentGraph/AtomComponentContainer.tsx
- src/app/components/ComponentGraph/AtomComponentVisual.tsx
- src/app/components/Metrics/RankedGraph.tsx
- src/app/components/SnapshotList/SnapshotList.tsx
- src/extension/build/stylesheet.css
- src/types/index.d.ts
- [x ] Bugfix (change which fixes an issue)
- [x ] New feature (change which adds functionality)
Took out visibility drop down feature in atom component graph. Added clickable legend with clickable dropdown features to atom component graph. Fixed actual duration times to show the actual times in snapshot list.
Refactored for an enhanced user experience.
> Clickable legend for Atom Network, fixed snapshot duration times, and removed visibility drop down menu.

- src/app/components/ComponentGraph/AtomComponentVisual.tsx
- [x ] Refactor (change which changes the codebase without affecting its external behavior)
Component graph hover text was all in one line.
Refactored D3 code to use foreignObject.
> Refactored Hover Text on D3 Component Graph

- src/app/components/AtomNetwork/AtomNetwork.tsx
refactor to reduce the use of any for typescript
found mouseevent for onclick event
> changed the event type to mouseevent

- src/app/Containers/MainContainer.tsx
- src/app/Containers/SnapshotContainer.tsx
- src/app/components/SnapshotList/SnapshotList.tsx
- src/extension/build/stylesheet.css
- src/types/index.d.ts
Implemented Previous and Forward clear buttons for snapshot list. Typescript stricter for actual duration times.
Added functionality where a user can clear their previous and forward snapshots from snapshot list.
> Added Previous and Forward Clear buttons to Snapshot List

- src/app/Containers/SnapshotContainer.tsx
- src/app/components/ComponentGraph/AtomComponentVisual.tsx
- src/app/components/Metrics/RankedGraph.tsx
- src/app/components/SnapshotList/SnapshotList.tsx
- src/app/components/StateDiff/Diff.tsx
- src/extension/build/stylesheet.css
Clear snapshot buttons weren't labeled clearly. Also indexing for clearing wasn't correct.
Included a Clear Snapshots title and renamed the clear buttons for easier comprehension. Fixed spacing between snapshots due to the removal of showing indexing. CSS styling and positioning changes in snapshots list.
> Snapshot list added title, better named clear buttons, snapshot list spacing and removal of indexing, css styling changes.

- src/app/components/ComponentGraph/AtomComponentVisual.tsx
- src/extension/build/stylesheet.css
add hover effect with d3 for each graph node and get back expand button on the bottom
added a div to add HTML element, div to add hover and revamp the expand button
> [component graph]changed the hover with div and reinserted the expand button

- src/app/components/ComponentGraph/AtomComponentVisual.tsx
- src/extension/build/stylesheet.css
add style for the text
add padding and next line for readability
> [compoent graph] stylized text in the hover div

- package.json
- package/index.js
- package/package.json
- src/app/Containers/SnapshotContainer.tsx
- src/app/components/AtomNetwork/AtomNetwork.tsx
- src/app/components/ComponentGraph/AtomComponentContainer.tsx
- src/app/components/ComponentGraph/AtomComponentVisual.tsx
- src/app/components/Metrics/FlameGraph.js
- src/app/components/Metrics/RankedGraph.tsx
- src/app/components/SnapshotList/SnapshotList.tsx
- src/app/components/StateDiff/Diff.tsx
- src/app/index.tsx
- src/app/utils/makeRelationshipLinks.ts
Removed unnecessary console logs and comments
Went through each file and deleted extraneous comments / console logs
> Removed Extraneous Console Logs

- src/extension/build/stylesheet.css
Hover text was too small.
Increased text size
> fixed hover text size in component graph

- package.json
- package/package.json
- src/extension/build/devtools.js
- src/extension/build/manifest.json
ready for upload
update the version number
> updated the version to 1.0.0

- README.md
Readme quotes were not programming style quotes so broke gifs.
Replaced to readable quotes.
> Fixed Readme quotes to programming style quotes

- README.md
Wrong version number in Readme
Updated version number in Readme to 1.0.0
> Updated version Recoilize in readme

- package/README.md
Updated Readme in package folder to reflect 1.0.0 update
> Updated Npm package
