- package/index.js
Co-authored-by: Taven Shumaker <tavensshumaker@gmail.com>
To Fix a bug resulting from Recoil 0.0.11 and above. (https://github.com/open-source-labs/Recoilize/issues/107)
To remove the need for a developer to pass in props to the debugger component.
Obtained nodeDependencies and nodeSubscriptions using new methods available in Recoil 0.0.13.
Used a new getNodes method from Recoil 0.0.13 to obtain initial atoms and selectors.
Included a conditional check to see if a developer is passing a root to the debugger component.
Used updated docs to learn about new API methods available in Recoil 0.0.13.
https://recoiljs.org/docs/api-reference/core/Snapshot
> Fixed bug related to Recoil 0.0.13

- src/app/Containers/VisualContainer.tsx
- src/app/components/App.tsx
- src/app/components/StateGraph/Visualizer.tsx
- src/extension/build/devtools.js
- src/extension/build/manifest.json
- src/types/index.d.ts
Co-authored-by: Aaron Yang <aaronyang024@gmail.com>
To replace the state graph tab with a metrics tab.
Renamed 'State Graph' to 'Metrics'. Removed the state graph visuals. Replaced the state nodes with the fiber tree nodes props.
Reviewed flow of data from the Recoilize npm module to the dev tool front-end.
> Removed state graph tab visuals and included Metrics

- src/app/Containers/MainContainer.tsx
- src/app/Containers/SnapshotContainer.tsx
- src/app/components/App.tsx
- src/app/components/SnapshotList/SnapshotList.tsx
The current Snapshot List does not contain any render times. To increase value to the developer, render times have been added to this section of the dev tool.
Obtained the updated actualDuration of each fiber tree every time a new snapshot was added to the snapshotList. Updated the div container to include this render time.
The filter array is built using jsondiffpatch. Read the following to understand how diff functions.
https://github.com/benjamine/jsondiffpatch
> Updates to include render times in the SnapshotList

- package/formatFiberNodes.js
- package/index.js
- src/app/Containers/SnapshotContainer.tsx
- src/app/Containers/VisualContainer.tsx
- src/app/components/SnapshotList/SnapshotList.tsx
- src/app/components/StateDiff/Diff.tsx
- src/extension/background.ts
- src/types/index.d.ts
Previously, the snapshots in the snapshot list contained indexes that would sometimes differ from the corresponding backend snapshot by one. This lead to any time-travel jump rendering the state of a different snapshot than desired to the browser.
On the backend, when the initialFilteredSnapshot is used to make the initial call to createDevToolData, a second argument is passed in; indexDiff. This contains the difference in length from 1 of the snapshots array (which should have a length of 1 on the the first time createDevToolData is called). This index diff is added as a prop to the devToolData object and passed to the front. On the front end instead of sending index to the backend to determine which snapshot to jump to, it passes index + indexDiff. This ensures that the index being …
> Fixed Off-By-One error in Time Travel

- package/index.js
- src/app/Containers/SnapshotContainer.tsx
Bug causing time travel debugging to be out of sync. Second step in the process of fixing it.
Updated package/index.js so that createDevToolData accepts the indexDiff parameter and adds it as a property to the filter being passed to the front end.
> Updated createDevToolData function in package/index.js to accept indexDiff parameter

- src/app/Containers/MainContainer.tsx
- src/app/Containers/SnapshotContainer.tsx
- src/app/components/App.tsx
- src/app/components/SnapshotList/SnapshotList.tsx
- src/types/index.d.ts
The dev tool was crashing whenever the website under inspection was reloaded.
The app was crashing because the snapshotList was expecting an object that had not yet been initialized. Rather than using the currenSnapshot value, the first element of snapshotHistory was used upon the first rendering of a webpage.
Console logs were utilized to inspect the value of filter, snapshotHistory, and currentSnapshot arrays to determine which should be used to log the very first render time on the dev tool.
> Fixed page reload dev tool crash.

- src/app/components/StateGraph/Visualizer.tsx
Bar graph was not updating on each render. 
The graph now displays each component render correctly. The name and duration of each corresponding component matches up accordingly.
Read documents on react hooks and how useState/useEffect works.
https://reactjs.org/docs/hooks-state.html
https://reactjs.org/docs/hooks-effect.html
> Fixed bug where graph would not update on re-renders

- src/app/components/StateGraph/Metrics.tsx
There are two separate graphs to display render times. A way to switch between them was needed.
A state variable was added (with useState hook) to Metrics.tsx which would hold true or false. A switch was rendered that toggles the state from true or false and depending on what state is either graph is conditionally rendered.
Using a switch element. First time diving into Aaron's code for the bar graph and attaching it to the rest of the metrics tab.
> Toggle Button added to Metrics tab to switch between graphs

- package/formatFiberNodes.js
- package/formatFiberNodes.ts
- src/app/components/SnapshotList/SnapshotList.tsx
- src/extension/build/stylesheet.css
- src/types/index.d.ts
To correct the render times being listed in the Snapshots section of the dev tool. Also to include styling for the jump button and add hovering effects.
A new key was created in the formattedFiberNodes object. TreeBaseDuration was added and used for the render times rather than using the actualBaseDuration.
A style attribute was added when the jump buttons are rendered in the js file and hover effects were corrected in the css file. Existing hover effects in the css file were not going into effect due to priority issues.
Reviewed the actualDuration and treeBaseDuration of the React Fiber Node as a team. Little documentation exists for these values and further research is required. For now, it was decided that the treeBaseDuration is the closest estimate to the render duration of the react …
> Render times list improvements.

- src/app/components/StateGraph/Visualizer.tsx
- src/extension/build/stylesheet.css
Graph was not resizing to fit window.
The graph is now changing relative to the window size.
> Updated bar graph to format to window size

- src/app/components/StateGraph/Metrics.tsx
Previously a switch was used to jump between the ranked graph and the icicle graph in the metrics tab. But this didn't describe at all what each graph was or its purpose.
Removed the switch and added 2 buttons that describe the graph displayed when clicked.
Read about flame graphs and ranked graphs to ensure that these were the correct names for the graphs based on the data that they describe.
> Updated graph toggle from a switch to more descriptive buttons

- src/app/components/ComponentGraph/AtomComponentVisual.tsx
The component graph legend would always show the suspense key. It was decided to only show this if a suspense component was actually rendered on the component graph.
Used ternary operators within the AtomComponentVisual returned divs that hold the legend keys. The conditional statement checks to see if a hasSuspense hook is true or false. If true a Suspense key is rendered in the legend.
Researched techniques for conditional rendering of div components. Ternary operators were the most efficient way for this situation. 
https://reactjs-bot.github.io/react/docs/lists-conditional-rendering.html
> Added conditional rendering for the suspense legend icon.

- src/app/components/SnapshotList/__tests__/SnapshotList.unit.test.js
The snapshotsList component lacks testing. It was decided to add several tests for each react component to achieve a more robust application.
A wrapper was created using enzyme shallow to render the HTML components of the SnapshotsList functional component. Jest built-in assertions were used to check accuracy of wrapper values. More test cases to come in a later PR. 
Researched implementation of jest, enzyme, and useful functionality such as mock functions. Shallow rendering was resulting in an error at first. Configuration for react 16 was required. This was accomplished by importing 'configure' from enzyme and 'adapter' from enzyme-adapter-react-16.
https://www.npmjs.com/package/enzyme-adapter-react-16
https://jestjs.io/docs/en/mock-functions
> Snapshot List testing progress.

- src/app/components/StateGraph/Metrics.tsx
- src/extension/build/stylesheet.css
- The metrics graph buttons were utilizing the same styling as time travel buttons, thus changes to either would affect both.
- The metrics graph buttons were not properly spaced.
- The neither metrics graph button was in focus on page load.
- Changed class names of metrics graph buttons and container, and provided those classes with own css styling.
- Added autoFocus attribute to the flamegraph button
Updated Buttons
Buttons Prior to Update
> Provided metrics graph buttons with their own styling.

- src/app/components/SnapshotList/__tests__/SnapshotList.unit.test.js
Test coverage for the SnapshotList component did not check for individual render time divs being rendered.
Leveraged jest enzyme built-in functionality to test the rendering of div elements containing the render times in the snapshotsList component. These div elements have class 'individualSnapshot' and so the hasClass function was used to return true whenever the class was found within a div container. 
Reviewed Jest enzyme functions such as hasClass() to check whether a div element has a particular class and first() which returns the first element within the iterable object resulting from find().
https://enzymejs.github.io/enzyme/docs/api/ShallowWrapper/hasClass.html
https://enzymejs.github.io/enzyme/docs/api/ReactWrapper/first.html
> Added more tests for the SnapshotList component.

- src/app/Containers/MainContainer.tsx
- src/app/components/ComponentGraph/AtomComponentVisual.tsx
The Recoilize dev tool would crash while on the Component Graph tab or the Metrics tab but only if there had been state changes recorded. The purpose of this was to look into why the crash was occurring and fix the crash.
The console error was flagging an undefined value with the hierarchy function used by d3. This function was invoked in AtomComponentVisual.tsx and it was noted that the data being passed in as a parameter was dependent on a react hooks state, renderIndex. 
The async behavior of setRenderIndex made it so that there was an instance where renderIndex was set to 0, but the previous value persisted for a moment while currentSnapshot was evaluated. This resulted in an undefined currentSnapshot. A ternary operator was utilized while defining currentSnapshot so that it could …
> Fixed page refresh dev tool crash

- src/app/components/Metrics/FlameGraph.js
- Prior to the change the flame graph didn't utilize color to display the data. The leaf nodes were colored and the rest of the graph was grey. This did nothing to help the user understand the data better.
- Utilized d3.interpolate to scale the color of each d3 node based on the actual duration of its corresponding component. To do this a function was introduced which calculated the average actualDuration of the entire tree and then the color was scaled based on component actualDuration relative to average actualDuration.
- Learned that there are many other uses for d3.interpolate, both with regard to colors and scaling of many other kinds.
https://bl.ocks.org/EfratVil/903d82a7cde553fb6739fe55af6103e2
https://github.com/d3/d3-interpolate
Updated graph with color
Visual of gradient …
> Added Duration based color scaling to Flamegraph

- package/formatFiberNodes.js
- package/formatFiberNodes.ts
The expanded component graph tree contained some nodes without any labels. This is because the name property had not been saved for  several components such as suspense components and context provider components. 
Updated the assignName function within formatFiberNodes to include a conditional return if the tag is equal to 13 (meaning that it is a suspense component) and a conditional return if the type key has a key of $$typeof. It was noted that some nodes that do not have a type.name property have a type.$$typeof property which holds a symbol with a component type key.
Read into the purpose of having $$typeof and then researched how to extract a key from a javascript symbol object.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol …
> Included missing graph component names

- package/formatFiberNodes.js
- src/app/components/Metrics/RankedGraph.tsx
There was no zoom feature or dragging ability in the ranked graph. The user would not be able to take a closer look at the render times and components names.
Added zoom and dragging functionality so that the user can resize and move the graph around.
https://www.d3-graph-gallery.com/graph/interactivity_zoom.html
> Added zoom and drag functionality to Ranked Graph

- src/app/Containers/VisualContainer.tsx
The initial component visuals were not including all of the functional components if they were suspended initially. 
Reviewed the fiber tree used by the backend to create the first snapshot. It was noted that the suspended components have tags of 2 which signifies an IndeterminateComponent. I included this tag to the cleanedComponent function which initially only selected nodes with a tag of 0.
> Included intermediate components in the visualizations

- src/app/components/Metrics/RankedGraph.tsx
The ranked graph was displaying the shorter durations to be a darker color than the longer durations. The darker color was also making it difficult to see the individual bar.
It makes more sense for the shorter durations to display a lighter shade and the longer durations to display a darker shade.
> Updated colors on ranked graph

- package/index.js
- src/app/Containers/SnapshotContainer.tsx
- src/app/components/Metrics/MetricsContainer.tsx
- src/app/components/Metrics/RankedGraph.tsx
- src/extension/background.ts
- src/extension/build/stylesheet.css
- src/extension/contentScript.ts
There were problems with the way the ranked graph scaled to the window, and when y-axis labels were too long the text would spill out of the window.
Utilized <parentSize> from the vx library to set the width and height of the svg, adjusted css styling of related elements, and added code to adjust the left margin based on the longest string of the y-axis labels. 
-Better understanding of the vx library and its features beyond parentSize
https://vx-demo.now.sh/docs/responsive
> Adjusted width setting of Ranked Graph

- package/index.js
The components and state being shown were always from the entire react fiber tree starting at id of 'root'. This was the case even when the user specified a different root.
Created a variable called recoilizeRoot to store the root. This was assigned a proper root inside a conditional statement.
Previously the variable, root, was being used but declarations occurred inside a conditional statement. This variable did not persist outside of the condition so when the variable 'root' was used downstream in the code javascript was interpreting it as document.getElementById('root'). This made it so that the react fiber tree would always start at id of 'root'.
Within the context of the DOM, root is defined as document.getElementById('root'). A different variable name was used to avoid uncaught …
> Added a recoilizeRoot variable to store the root.
